- name: variables to print
  hosts: web
  vars:
    COURSE: "DEVOPS with AWS"
    TRAINER: "Mansoor"
    DURATION: "120 Hours"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I'm Learning {{COURSE}}, from Trainer:{{TRAINER}}, Duration:{{DURATION}}"
      

      
