- name: Variables type play tasks
  hosts: web
  vars: #play level vars can be accessed in all task of this play
    COURSE: "Devops With AWS"
    TRAINER: "Siva Kumar"
    DURATION: "120 Hours"
  tasks:
  - name: print play level variables
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{COURSE}}, From {{TRAINER}}, Duration:{{DURATION}}"

  - name: print task level variables
    vars:
      COURSE: "Ansible"   #task level vars 
    ansible.builtin.debug:
      msg: "Hi, I'm Learning {{COURSE}}, From Trainer:{{TRAINER}}, Duration:{{DURATION}}"

  - name: print play level vars again
    ansible.builtin.debug:
      msg: "Hi, I'm Learning {{COURSE}} from {{TRAINER}}, Duration:{{DURATION}}"