- name: variables from file
  hosts: web
  vars_files:
  - vars.yaml
  tasks: 
  - name: print the variables from file
    ansible.builtin.debug:
      msg: "Hi, I'm learning{{COURSE}},from Trainer:{{TRAINER}}, duration:{{DURATION}}"

