- name: vars from inventory
  hosts: web
  tasks: 
  - name: vars from inventory
    ansible.builtin.debug:
      msg: "Hi, I'm Learning Course:{{COURSE}},From Trainer:{{TRAINER}}, duration:{{DURATION}}"
