- name: vars priority
  hosts: web
  vars:
    COURSE: Devops
  vars_files:
  - vars.yaml
  #5vars_prompt:
  #- name: COURSE
    #prompt: Please enter course name
  tasks:
  - name: print variables priority
    vars:
   #2   COURSE: TASK-level
    ansible.builtin.debug:
      msg: "Hi Iam learning: {{COURSE}}"


#priority order
#1-vars passed as args
#2-vars declared at task-level
#3-vars from file
#4-vars from prompt
#5-vars from play-level
#6-vars from inventory
